---
  - hosts: all
    become: true
    tasks:
      - name: Replace a line in a file
        ansible.builtin.lineinfile:
          path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
          regexp: "^Ext.Msg.show({$"         
          line: "void({"
