---
- hosts: all
  tasks:
    - name: Fix no vaild subscription
      ansible.builtin.lineinfile:
        path: /usr/share/javascript/proxmox-widget-toolkit/test2.txt
        regexp: '^Hej'
        line: void
